// Autogenerated by gen-tz-data.py. Do not modify.
#ifndef X_DATETIME_TIMEZONE_H
#define X_DATETIME_TIMEZONE_H
#include <string>
#include <map>
#include <vector>
#include <time.h>
namespace xDateTime {
struct Timezone {
    std::string name;
    std::vector<time_t> utc;
    std::vector<time_t> local;
    std::vector<std::string> tzname;
    std::vector<int> dst;
    std::vector<int> gmtoff; // seconds
    static std::string CalcOffset(int hour, int minute) {
        std::string n = std::to_string(hour) + ((minute > 0) ? ":" + std::to_string(minute) : "");
        n.insert(0, hour < 0 ? "UTC-" : "UTC+");
        return n;
    }
    Timezone() {}
    Timezone(int hour, int minute) {
        name = Timezone::CalcOffset(hour, minute);
        gmtoff.push_back(minute * 60 + hour * 60 * 60);
    }
    Timezone(const std::string& name_, int hour, int minute) {
        name = name_;
        gmtoff.push_back(minute * 60 + hour * 60 * 60);
    }
};

static inline std::map<std::string, Timezone> InitializeTimezones();
static inline Timezone TZ(const std::string& name) { return InitializeTimezones()[name]; }
struct BaseTimezone {
    Timezone tz;
    BaseTimezone() { tz = TZ("UTC"); }
};

static inline std::map<std::string, Timezone> InitializeTimezones() {
    static std::map<std::string, Timezone> timezones; 
    static bool initialized = false; 
    struct tm t;
    if (initialized) return timezones;

    // Cities markes as time zone reference points
    // Note: None of these conversions allow auto DST because we apply it ourselves
    // based on the info we have handy.
    // Time zone offsets from UTC
    timezones[Timezone::CalcOffset(-12, 0)] = Timezone(-12, 0);
    timezones[Timezone::CalcOffset(-12, 15)] = Timezone(-12, 15);
    timezones[Timezone::CalcOffset(-12, 30)] = Timezone(-12, 30);
    timezones[Timezone::CalcOffset(-12, 45)] = Timezone(-12, 45);
    timezones[Timezone::CalcOffset(-11, 0)] = Timezone(-11, 0);
    timezones[Timezone::CalcOffset(-11, 15)] = Timezone(-11, 15);
    timezones[Timezone::CalcOffset(-11, 30)] = Timezone(-11, 30);
    timezones[Timezone::CalcOffset(-11, 45)] = Timezone(-11, 45);
    timezones[Timezone::CalcOffset(-10, 0)] = Timezone(-10, 0);
    timezones[Timezone::CalcOffset(-10, 15)] = Timezone(-10, 15);
    timezones[Timezone::CalcOffset(-10, 30)] = Timezone(-10, 30);
    timezones[Timezone::CalcOffset(-10, 45)] = Timezone(-10, 45);
    timezones[Timezone::CalcOffset(-9, 0)] = Timezone(-9, 0);
    timezones[Timezone::CalcOffset(-9, 15)] = Timezone(-9, 15);
    timezones[Timezone::CalcOffset(-9, 30)] = Timezone(-9, 30);
    timezones[Timezone::CalcOffset(-9, 45)] = Timezone(-9, 45);
    timezones[Timezone::CalcOffset(-8, 0)] = Timezone(-8, 0);
    timezones[Timezone::CalcOffset(-8, 15)] = Timezone(-8, 15);
    timezones[Timezone::CalcOffset(-8, 30)] = Timezone(-8, 30);
    timezones[Timezone::CalcOffset(-8, 45)] = Timezone(-8, 45);
    timezones[Timezone::CalcOffset(-7, 0)] = Timezone(-7, 0);
    timezones[Timezone::CalcOffset(-7, 15)] = Timezone(-7, 15);
    timezones[Timezone::CalcOffset(-7, 30)] = Timezone(-7, 30);
    timezones[Timezone::CalcOffset(-7, 45)] = Timezone(-7, 45);
    timezones[Timezone::CalcOffset(-6, 0)] = Timezone(-6, 0);
    timezones[Timezone::CalcOffset(-6, 15)] = Timezone(-6, 15);
    timezones[Timezone::CalcOffset(-6, 30)] = Timezone(-6, 30);
    timezones[Timezone::CalcOffset(-6, 45)] = Timezone(-6, 45);
    timezones[Timezone::CalcOffset(-5, 0)] = Timezone(-5, 0);
    timezones[Timezone::CalcOffset(-5, 15)] = Timezone(-5, 15);
    timezones[Timezone::CalcOffset(-5, 30)] = Timezone(-5, 30);
    timezones[Timezone::CalcOffset(-5, 45)] = Timezone(-5, 45);
    timezones[Timezone::CalcOffset(-4, 0)] = Timezone(-4, 0);
    timezones[Timezone::CalcOffset(-4, 15)] = Timezone(-4, 15);
    timezones[Timezone::CalcOffset(-4, 30)] = Timezone(-4, 30);
    timezones[Timezone::CalcOffset(-4, 45)] = Timezone(-4, 45);
    timezones[Timezone::CalcOffset(-3, 0)] = Timezone(-3, 0);
    timezones[Timezone::CalcOffset(-3, 15)] = Timezone(-3, 15);
    timezones[Timezone::CalcOffset(-3, 30)] = Timezone(-3, 30);
    timezones[Timezone::CalcOffset(-3, 45)] = Timezone(-3, 45);
    timezones[Timezone::CalcOffset(-2, 0)] = Timezone(-2, 0);
    timezones[Timezone::CalcOffset(-2, 15)] = Timezone(-2, 15);
    timezones[Timezone::CalcOffset(-2, 30)] = Timezone(-2, 30);
    timezones[Timezone::CalcOffset(-2, 45)] = Timezone(-2, 45);
    timezones[Timezone::CalcOffset(-1, 0)] = Timezone(-1, 0);
    timezones[Timezone::CalcOffset(-1, 15)] = Timezone(-1, 15);
    timezones[Timezone::CalcOffset(-1, 30)] = Timezone(-1, 30);
    timezones[Timezone::CalcOffset(-1, 45)] = Timezone(-1, 45);
    timezones[Timezone::CalcOffset(0, 0)] = Timezone(0, 0);
    timezones[Timezone::CalcOffset(0, 15)] = Timezone(0, 15);
    timezones[Timezone::CalcOffset(0, 30)] = Timezone(0, 30);
    timezones[Timezone::CalcOffset(0, 45)] = Timezone(0, 45);
    timezones[Timezone::CalcOffset(1, 0)] = Timezone(1, 0);
    timezones[Timezone::CalcOffset(1, 15)] = Timezone(1, 15);
    timezones[Timezone::CalcOffset(1, 30)] = Timezone(1, 30);
    timezones[Timezone::CalcOffset(1, 45)] = Timezone(1, 45);
    timezones[Timezone::CalcOffset(2, 0)] = Timezone(2, 0);
    timezones[Timezone::CalcOffset(2, 15)] = Timezone(2, 15);
    timezones[Timezone::CalcOffset(2, 30)] = Timezone(2, 30);
    timezones[Timezone::CalcOffset(2, 45)] = Timezone(2, 45);
    timezones[Timezone::CalcOffset(3, 0)] = Timezone(3, 0);
    timezones[Timezone::CalcOffset(3, 15)] = Timezone(3, 15);
    timezones[Timezone::CalcOffset(3, 30)] = Timezone(3, 30);
    timezones[Timezone::CalcOffset(3, 45)] = Timezone(3, 45);
    timezones[Timezone::CalcOffset(4, 0)] = Timezone(4, 0);
    timezones[Timezone::CalcOffset(4, 15)] = Timezone(4, 15);
    timezones[Timezone::CalcOffset(4, 30)] = Timezone(4, 30);
    timezones[Timezone::CalcOffset(4, 45)] = Timezone(4, 45);
    timezones[Timezone::CalcOffset(5, 0)] = Timezone(5, 0);
    timezones[Timezone::CalcOffset(5, 15)] = Timezone(5, 15);
    timezones[Timezone::CalcOffset(5, 30)] = Timezone(5, 30);
    timezones[Timezone::CalcOffset(5, 45)] = Timezone(5, 45);
    timezones[Timezone::CalcOffset(6, 0)] = Timezone(6, 0);
    timezones[Timezone::CalcOffset(6, 15)] = Timezone(6, 15);
    timezones[Timezone::CalcOffset(6, 30)] = Timezone(6, 30);
    timezones[Timezone::CalcOffset(6, 45)] = Timezone(6, 45);
    timezones[Timezone::CalcOffset(7, 0)] = Timezone(7, 0);
    timezones[Timezone::CalcOffset(7, 15)] = Timezone(7, 15);
    timezones[Timezone::CalcOffset(7, 30)] = Timezone(7, 30);
    timezones[Timezone::CalcOffset(7, 45)] = Timezone(7, 45);
    timezones[Timezone::CalcOffset(8, 0)] = Timezone(8, 0);
    timezones[Timezone::CalcOffset(8, 15)] = Timezone(8, 15);
    timezones[Timezone::CalcOffset(8, 30)] = Timezone(8, 30);
    timezones[Timezone::CalcOffset(8, 45)] = Timezone(8, 45);
    timezones[Timezone::CalcOffset(9, 0)] = Timezone(9, 0);
    timezones[Timezone::CalcOffset(9, 15)] = Timezone(9, 15);
    timezones[Timezone::CalcOffset(9, 30)] = Timezone(9, 30);
    timezones[Timezone::CalcOffset(9, 45)] = Timezone(9, 45);
    timezones[Timezone::CalcOffset(10, 0)] = Timezone(10, 0);
    timezones[Timezone::CalcOffset(10, 15)] = Timezone(10, 15);
    timezones[Timezone::CalcOffset(10, 30)] = Timezone(10, 30);
    timezones[Timezone::CalcOffset(10, 45)] = Timezone(10, 45);
    timezones[Timezone::CalcOffset(11, 0)] = Timezone(11, 0);
    timezones[Timezone::CalcOffset(11, 15)] = Timezone(11, 15);
    timezones[Timezone::CalcOffset(11, 30)] = Timezone(11, 30);
    timezones[Timezone::CalcOffset(11, 45)] = Timezone(11, 45);
    timezones[Timezone::CalcOffset(12, 0)] = Timezone(12, 0);
    timezones[Timezone::CalcOffset(12, 15)] = Timezone(12, 15);
    timezones[Timezone::CalcOffset(12, 30)] = Timezone(12, 30);
    timezones[Timezone::CalcOffset(12, 45)] = Timezone(12, 45);
    timezones[Timezone::CalcOffset(13, 0)] = Timezone(13, 0);
    timezones[Timezone::CalcOffset(13, 15)] = Timezone(13, 15);
    timezones[Timezone::CalcOffset(13, 30)] = Timezone(13, 30);
    timezones[Timezone::CalcOffset(13, 45)] = Timezone(13, 45);
    timezones[Timezone::CalcOffset(14, 0)] = Timezone(14, 0);
    timezones[Timezone::CalcOffset(14, 15)] = Timezone(14, 15);
    timezones[Timezone::CalcOffset(14, 30)] = Timezone(14, 30);
    timezones[Timezone::CalcOffset(14, 45)] = Timezone(14, 45);

    // Time zone names
    timezones["ACDT"] = Timezone("ACDT", 10, 30);
    timezones["ACST"] = Timezone("ACST", 9, 30);
    timezones["ACT"] = Timezone("ACT", 8, 0);
    timezones["ACWST"] = Timezone("ACWST", 8, 45);
    timezones["ADT"] = Timezone("ADT", 3, 0);
    timezones["AEDT"] = Timezone("AEDT", 11, 0);
    timezones["AEST"] = Timezone("AEST", 10, 0);
    timezones["AFT"] = Timezone("AFT", 4, 30);
    timezones["AKDT"] = Timezone("AKDT", 8, 0);
    timezones["AKST"] = Timezone("AKST", 9, 0);
    timezones["ALMT"] = Timezone("ALMT", 6, 0);
    timezones["AMST"] = Timezone("AMST", 3, 0);
    timezones["AMT"] = Timezone("AMT", 4, 0);
    timezones["ANAT"] = Timezone("ANAT", 12, 0);
    timezones["AQTT"] = Timezone("AQTT", 5, 0);
    timezones["ART"] = Timezone("ART", 3, 0);
    timezones["ASEAN Common Time"] = Timezone("ASEAN Common Time", 8, 0);
    timezones["AST"] = Timezone("AST", 4, 0);
    timezones["AWST"] = Timezone("AWST", 8, 0);
    timezones["AZOST"] = Timezone("AZOST", 0, 0);
    timezones["AZOT"] = Timezone("AZOT", 1, 0);
    timezones["AZT"] = Timezone("AZT", 4, 0);
    timezones["Acre Time"] = Timezone("Acre Time", 5, 0);
    timezones["Afghanistan Time"] = Timezone("Afghanistan Time", 4, 30);
    timezones["Alaska Daylight Time"] = Timezone("Alaska Daylight Time", 8, 0);
    timezones["Alaska Standard Time"] = Timezone("Alaska Standard Time", 9, 0);
    timezones["Alma-Ata Time"] = Timezone("Alma-Ata Time", 6, 0);
    timezones["Amazon Summer Time"] = Timezone("Amazon Summer Time", 3, 0);
    timezones["Amazon Time"] = Timezone("Amazon Time", 4, 0);
    timezones["Anadyr Time"] = Timezone("Anadyr Time", 12, 0);
    timezones["Aqtobe Time"] = Timezone("Aqtobe Time", 5, 0);
    timezones["Arabia Standard Time"] = Timezone("Arabia Standard Time", 3, 0);
    timezones["Argentina Time"] = Timezone("Argentina Time", 3, 0);
    timezones["Armenia Time"] = Timezone("Armenia Time", 4, 0);
    timezones["Atlantic Daylight Time"] = Timezone("Atlantic Daylight Time", 3, 0);
    timezones["Atlantic Standard Time"] = Timezone("Atlantic Standard Time", 4, 0);
    timezones["Australian Central Daylight Saving Time"] = Timezone("Australian Central Daylight Saving Time", 10, 30);
    timezones["Australian Central Standard Time"] = Timezone("Australian Central Standard Time", 9, 30);
    timezones["Australian Central Western Standard Time"] = Timezone("Australian Central Western Standard Time", 8, 45);
    timezones["Australian Eastern Daylight Saving Time"] = Timezone("Australian Eastern Daylight Saving Time", 11, 0);
    timezones["Australian Eastern Standard Time"] = Timezone("Australian Eastern Standard Time", 10, 0);
    timezones["Australian Western Standard Time"] = Timezone("Australian Western Standard Time", 8, 0);
    timezones["Azerbaijan Time"] = Timezone("Azerbaijan Time", 4, 0);
    timezones["Azores Standard Time"] = Timezone("Azores Standard Time", 1, 0);
    timezones["Azores Summer Time"] = Timezone("Azores Summer Time", 0, 0);
    timezones["BIOT"] = Timezone("BIOT", 6, 0);
    timezones["BIT"] = Timezone("BIT", 12, 0);
    timezones["BNT"] = Timezone("BNT", 8, 0);
    timezones["BOT"] = Timezone("BOT", 4, 0);
    timezones["BRST"] = Timezone("BRST", 2, 0);
    timezones["BRT"] = Timezone("BRT", 3, 0);
    timezones["BST"] = Timezone("BST", 1, 0);
    timezones["BTT"] = Timezone("BTT", 6, 0);
    timezones["Baker Island Time"] = Timezone("Baker Island Time", 12, 0);
    timezones["Bangladesh Standard Time"] = Timezone("Bangladesh Standard Time", 6, 0);
    timezones["Bhutan Time"] = Timezone("Bhutan Time", 6, 0);
    timezones["Bolivia Time"] = Timezone("Bolivia Time", 4, 0);
    timezones["Bougainville Standard Time"] = Timezone("Bougainville Standard Time", 11, 0);
    timezones["Brasília Summer Time"] = Timezone("Brasília Summer Time", 2, 0);
    timezones["Brasília Time"] = Timezone("Brasília Time", 3, 0);
    timezones["British Indian Ocean Time"] = Timezone("British Indian Ocean Time", 6, 0);
    timezones["British Summer Time"] = Timezone("British Summer Time", 1, 0);
    timezones["Brunei Time"] = Timezone("Brunei Time", 8, 0);
    timezones["CAT"] = Timezone("CAT", 2, 0);
    timezones["CCT"] = Timezone("CCT", 6, 30);
    timezones["CDT"] = Timezone("CDT", 4, 0);
    timezones["CEST"] = Timezone("CEST", 2, 0);
    timezones["CET"] = Timezone("CET", 1, 0);
    timezones["CHADT"] = Timezone("CHADT", 13, 45);
    timezones["CHAST"] = Timezone("CHAST", 12, 45);
    timezones["CHOST"] = Timezone("CHOST", 9, 0);
    timezones["CHOT"] = Timezone("CHOT", 8, 0);
    timezones["CHST"] = Timezone("CHST", 10, 0);
    timezones["CHUT"] = Timezone("CHUT", 10, 0);
    timezones["CIST"] = Timezone("CIST", 8, 0);
    timezones["CKT"] = Timezone("CKT", 10, 0);
    timezones["CLST"] = Timezone("CLST", 3, 0);
    timezones["CLT"] = Timezone("CLT", 4, 0);
    timezones["COST"] = Timezone("COST", 4, 0);
    timezones["COT"] = Timezone("COT", 5, 0);
    timezones["CST"] = Timezone("CST", 5, 0);
    timezones["CVT"] = Timezone("CVT", 1, 0);
    timezones["CWST"] = Timezone("CWST", 8, 45);
    timezones["CXT"] = Timezone("CXT", 7, 0);
    timezones["Cape Verde Time"] = Timezone("Cape Verde Time", 1, 0);
    timezones["Central Africa Time"] = Timezone("Central Africa Time", 2, 0);
    timezones["Central Daylight Time"] = Timezone("Central Daylight Time", 5, 0);
    timezones["Central European Summer Time"] = Timezone("Central European Summer Time", 2, 0);
    timezones["Central European Time"] = Timezone("Central European Time", 1, 0);
    timezones["Central Indonesia Time"] = Timezone("Central Indonesia Time", 8, 0);
    timezones["Central Standard Time"] = Timezone("Central Standard Time", 6, 0);
    timezones["Central Western Standard Time"] = Timezone("Central Western Standard Time", 8, 45);
    timezones["Chagos Archipelago|Indian Ocean Time"] = Timezone("Chagos Archipelago|Indian Ocean Time", 3, 0);
    timezones["Chamorro Standard Time"] = Timezone("Chamorro Standard Time", 10, 0);
    timezones["Chatham Daylight Time"] = Timezone("Chatham Daylight Time", 13, 45);
    timezones["Chatham Standard Time"] = Timezone("Chatham Standard Time", 12, 45);
    timezones["Chile Standard Time"] = Timezone("Chile Standard Time", 4, 0);
    timezones["Chile Summer Time"] = Timezone("Chile Summer Time", 3, 0);
    timezones["China Standard Time"] = Timezone("China Standard Time", 8, 0);
    timezones["Choibalsan Standard Time"] = Timezone("Choibalsan Standard Time", 8, 0);
    timezones["Choibalsan Summer Time"] = Timezone("Choibalsan Summer Time", 9, 0);
    timezones["Christmas Island Time"] = Timezone("Christmas Island Time", 7, 0);
    timezones["Chuuk Time"] = Timezone("Chuuk Time", 10, 0);
    timezones["Clipperton Island Standard Time"] = Timezone("Clipperton Island Standard Time", 8, 0);
    timezones["Cocos Islands Time"] = Timezone("Cocos Islands Time", 6, 30);
    timezones["Colombia Summer Time"] = Timezone("Colombia Summer Time", 4, 0);
    timezones["Colombia Time"] = Timezone("Colombia Time", 5, 0);
    timezones["Cook Island Time"] = Timezone("Cook Island Time", 10, 0);
    timezones["Coordinated Universal Time"] = Timezone("Coordinated Universal Time", 0, 0);
    timezones["Cuba Daylight Time"] = Timezone("Cuba Daylight Time", 4, 0);
    timezones["Cuba Standard Time"] = Timezone("Cuba Standard Time", 5, 0);
    timezones["DAVT"] = Timezone("DAVT", 7, 0);
    timezones["DDUT"] = Timezone("DDUT", 10, 0);
    timezones["DFT"] = Timezone("DFT", 1, 0);
    timezones["Davis Time"] = Timezone("Davis Time", 7, 0);
    timezones["Dumont d'Urville Time"] = Timezone("Dumont d'Urville Time", 10, 0);
    timezones["EASST"] = Timezone("EASST", 5, 0);
    timezones["EAST"] = Timezone("EAST", 6, 0);
    timezones["EAT"] = Timezone("EAT", 3, 0);
    timezones["ECT"] = Timezone("ECT", 5, 0);
    timezones["EDT"] = Timezone("EDT", 4, 0);
    timezones["EEST"] = Timezone("EEST", 3, 0);
    timezones["EET"] = Timezone("EET", 2, 0);
    timezones["EGST"] = Timezone("EGST", 0, 0);
    timezones["EGT"] = Timezone("EGT", 1, 0);
    timezones["EST"] = Timezone("EST", 5, 0);
    timezones["East Africa Time"] = Timezone("East Africa Time", 3, 0);
    timezones["Easter Island Standard Time"] = Timezone("Easter Island Standard Time", 6, 0);
    timezones["Easter Island Summer Time"] = Timezone("Easter Island Summer Time", 5, 0);
    timezones["Eastern Caribbean Time"] = Timezone("Eastern Caribbean Time", 4, 0);
    timezones["Eastern Daylight Time"] = Timezone("Eastern Daylight Time", 4, 0);
    timezones["Eastern European Summer Time"] = Timezone("Eastern European Summer Time", 3, 0);
    timezones["Eastern European Time"] = Timezone("Eastern European Time", 2, 0);
    timezones["Eastern Greenland Summer Time"] = Timezone("Eastern Greenland Summer Time", 0, 0);
    timezones["Eastern Greenland Time"] = Timezone("Eastern Greenland Time", 1, 0);
    timezones["Eastern Indonesian Time"] = Timezone("Eastern Indonesian Time", 9, 0);
    timezones["Eastern Standard Time"] = Timezone("Eastern Standard Time", 5, 0);
    timezones["Ecuador Time"] = Timezone("Ecuador Time", 5, 0);
    timezones["FET"] = Timezone("FET", 3, 0);
    timezones["FJT"] = Timezone("FJT", 12, 0);
    timezones["FKST"] = Timezone("FKST", 3, 0);
    timezones["FKT"] = Timezone("FKT", 4, 0);
    timezones["FNT"] = Timezone("FNT", 2, 0);
    timezones["Falkland Islands Summer Time"] = Timezone("Falkland Islands Summer Time", 3, 0);
    timezones["Falkland Islands Time"] = Timezone("Falkland Islands Time", 4, 0);
    timezones["Fernando de Noronha Time"] = Timezone("Fernando de Noronha Time", 2, 0);
    timezones["Fiji Time"] = Timezone("Fiji Time", 12, 0);
    timezones["French Guiana Time"] = Timezone("French Guiana Time", 3, 0);
    timezones["French Southern and Antarctic Time"] = Timezone("French Southern and Antarctic Time", 5, 0);
    timezones["Further-eastern European Time"] = Timezone("Further-eastern European Time", 3, 0);
    timezones["GALT"] = Timezone("GALT", 6, 0);
    timezones["GAMT"] = Timezone("GAMT", 9, 0);
    timezones["GET"] = Timezone("GET", 4, 0);
    timezones["GFT"] = Timezone("GFT", 3, 0);
    timezones["GILT"] = Timezone("GILT", 12, 0);
    timezones["GIT"] = Timezone("GIT", 9, 0);
    timezones["GMT"] = Timezone("GMT", 0, 0);
    timezones["GST"] = Timezone("GST", 4, 0);
    timezones["GYT"] = Timezone("GYT", 4, 0);
    timezones["Galápagos Time"] = Timezone("Galápagos Time", 6, 0);
    timezones["Gambier Island Time"] = Timezone("Gambier Island Time", 9, 0);
    timezones["Gambier Islands Time"] = Timezone("Gambier Islands Time", 9, 0);
    timezones["Georgia Standard Time"] = Timezone("Georgia Standard Time", 4, 0);
    timezones["Gilbert Island Time"] = Timezone("Gilbert Island Time", 12, 0);
    timezones["Greenwich Mean Time"] = Timezone("Greenwich Mean Time", 0, 0);
    timezones["Gulf Standard Time"] = Timezone("Gulf Standard Time", 4, 0);
    timezones["Guyana Time"] = Timezone("Guyana Time", 4, 0);
    timezones["HAEC"] = Timezone("HAEC", 2, 0);
    timezones["HDT"] = Timezone("HDT", 9, 0);
    timezones["HKT"] = Timezone("HKT", 8, 0);
    timezones["HMT"] = Timezone("HMT", 5, 0);
    timezones["HOVST"] = Timezone("HOVST", 8, 0);
    timezones["HOVT"] = Timezone("HOVT", 7, 0);
    timezones["HST"] = Timezone("HST", 10, 0);
    timezones["Hawaii–Aleutian Daylight Time"] = Timezone("Hawaii–Aleutian Daylight Time", 9, 0);
    timezones["Hawaii–Aleutian Standard Time"] = Timezone("Hawaii–Aleutian Standard Time", 10, 0);
    timezones["Heard and McDonald Islands"] = Timezone("Heard and McDonald Islands", 5, 0);
    timezones["Heure Avancée d'Europe Centrale"] = Timezone("Heure Avancée d'Europe Centrale", 2, 0);
    timezones["Hong Kong Time"] = Timezone("Hong Kong Time", 8, 0);
    timezones["Hovd Summer Time"] = Timezone("Hovd Summer Time", 8, 0);
    timezones["Hovd Time"] = Timezone("Hovd Time", 7, 0);
    timezones["ICT"] = Timezone("ICT", 7, 0);
    timezones["IDLW"] = Timezone("IDLW", 12, 0);
    timezones["IDT"] = Timezone("IDT", 3, 0);
    timezones["IOT"] = Timezone("IOT", 3, 0);
    timezones["IRDT"] = Timezone("IRDT", 4, 30);
    timezones["IRKT"] = Timezone("IRKT", 8, 0);
    timezones["IRST"] = Timezone("IRST", 3, 30);
    timezones["IST"] = Timezone("IST", 2, 0);
    timezones["Indian Standard Time"] = Timezone("Indian Standard Time", 5, 30);
    timezones["Indochina Time"] = Timezone("Indochina Time", 7, 0);
    timezones["Iran Daylight Time"] = Timezone("Iran Daylight Time", 4, 30);
    timezones["Iran Standard Time"] = Timezone("Iran Standard Time", 3, 30);
    timezones["Irish Standard Time"] = Timezone("Irish Standard Time", 1, 0);
    timezones["Irkutsk Time"] = Timezone("Irkutsk Time", 8, 0);
    timezones["Israel Daylight Time"] = Timezone("Israel Daylight Time", 3, 0);
    timezones["Israel Standard Time"] = Timezone("Israel Standard Time", 2, 0);
    timezones["JST"] = Timezone("JST", 9, 0);
    timezones["Japan Standard Time"] = Timezone("Japan Standard Time", 9, 0);
    timezones["KALT"] = Timezone("KALT", 2, 0);
    timezones["KGT"] = Timezone("KGT", 6, 0);
    timezones["KOST"] = Timezone("KOST", 11, 0);
    timezones["KRAT"] = Timezone("KRAT", 7, 0);
    timezones["KST"] = Timezone("KST", 9, 0);
    timezones["Kaliningrad Time"] = Timezone("Kaliningrad Time", 2, 0);
    timezones["Kamchatka Time"] = Timezone("Kamchatka Time", 12, 0);
    timezones["Korea Standard Time"] = Timezone("Korea Standard Time", 9, 0);
    timezones["Kosrae Time"] = Timezone("Kosrae Time", 11, 0);
    timezones["Krasnoyarsk Time"] = Timezone("Krasnoyarsk Time", 7, 0);
    timezones["Kyrgyzstan Time"] = Timezone("Kyrgyzstan Time", 6, 0);
    timezones["LHST"] = Timezone("LHST", 11, 0);
    timezones["LINT"] = Timezone("LINT", 14, 0);
    timezones["Line Islands"] = Timezone("Line Islands", 14, 0);
    timezones["Lord Howe Standard Time"] = Timezone("Lord Howe Standard Time", 10, 30);
    timezones["Lord Howe Summer Time"] = Timezone("Lord Howe Summer Time", 11, 0);
    timezones["MAGT"] = Timezone("MAGT", 12, 0);
    timezones["MART"] = Timezone("MART", 9, 30);
    timezones["MAWT"] = Timezone("MAWT", 5, 0);
    timezones["MDT"] = Timezone("MDT", 6, 0);
    timezones["MEST"] = Timezone("MEST", 2, 0);
    timezones["MET"] = Timezone("MET", 1, 0);
    timezones["MHT"] = Timezone("MHT", 12, 0);
    timezones["MIST"] = Timezone("MIST", 11, 0);
    timezones["MIT"] = Timezone("MIT", 9, 30);
    timezones["MMT"] = Timezone("MMT", 6, 30);
    timezones["MSK"] = Timezone("MSK", 3, 0);
    timezones["MST"] = Timezone("MST", 7, 0);
    timezones["MUT"] = Timezone("MUT", 4, 0);
    timezones["MVT"] = Timezone("MVT", 5, 0);
    timezones["MYT"] = Timezone("MYT", 8, 0);
    timezones["Macquarie Island Station Time"] = Timezone("Macquarie Island Station Time", 11, 0);
    timezones["Magadan Time"] = Timezone("Magadan Time", 12, 0);
    timezones["Malaysia Standard Time"] = Timezone("Malaysia Standard Time", 8, 0);
    timezones["Malaysia Time"] = Timezone("Malaysia Time", 8, 0);
    timezones["Maldives Time"] = Timezone("Maldives Time", 5, 0);
    timezones["Marquesas Islands Time"] = Timezone("Marquesas Islands Time", 9, 30);
    timezones["Marshall Islands Time"] = Timezone("Marshall Islands Time", 12, 0);
    timezones["Mauritius Time"] = Timezone("Mauritius Time", 4, 0);
    timezones["Mawson Station Time"] = Timezone("Mawson Station Time", 5, 0);
    timezones["Middle European Summer Time"] = Timezone("Middle European Summer Time", 2, 0);
    timezones["Middle European Time"] = Timezone("Middle European Time", 1, 0);
    timezones["Moscow Time"] = Timezone("Moscow Time", 3, 0);
    timezones["Mountain Daylight Time"] = Timezone("Mountain Daylight Time", 6, 0);
    timezones["Mountain Standard Time"] = Timezone("Mountain Standard Time", 7, 0);
    timezones["Myanmar Standard Time"] = Timezone("Myanmar Standard Time", 6, 30);
    timezones["NCT"] = Timezone("NCT", 11, 0);
    timezones["NDT"] = Timezone("NDT", 2, 30);
    timezones["NFT"] = Timezone("NFT", 11, 0);
    timezones["NOVT"] = Timezone("NOVT", 7, 0);
    timezones["NPT"] = Timezone("NPT", 5, 45);
    timezones["NST"] = Timezone("NST", 3, 30);
    timezones["NT"] = Timezone("NT", 3, 30);
    timezones["NUT"] = Timezone("NUT", 11, 0);
    timezones["NZDT"] = Timezone("NZDT", 13, 0);
    timezones["NZST"] = Timezone("NZST", 12, 0);
    timezones["Nepal Time"] = Timezone("Nepal Time", 5, 45);
    timezones["New Caledonia Time"] = Timezone("New Caledonia Time", 11, 0);
    timezones["New Zealand Daylight Time"] = Timezone("New Zealand Daylight Time", 13, 0);
    timezones["New Zealand Standard Time"] = Timezone("New Zealand Standard Time", 12, 0);
    timezones["Newfoundland Daylight Time"] = Timezone("Newfoundland Daylight Time", 2, 30);
    timezones["Newfoundland Standard Time"] = Timezone("Newfoundland Standard Time", 3, 30);
    timezones["Newfoundland Time"] = Timezone("Newfoundland Time", 3, 30);
    timezones["Niue Time"] = Timezone("Niue Time", 11, 0);
    timezones["Norfolk Island Time"] = Timezone("Norfolk Island Time", 11, 0);
    timezones["Novosibirsk Time "] = Timezone("Novosibirsk Time ", 7, 0);
    timezones["OMST"] = Timezone("OMST", 6, 0);
    timezones["ORAT"] = Timezone("ORAT", 5, 0);
    timezones["Omsk Time"] = Timezone("Omsk Time", 6, 0);
    timezones["Oral Time"] = Timezone("Oral Time", 5, 0);
    timezones["PDT"] = Timezone("PDT", 7, 0);
    timezones["PET"] = Timezone("PET", 5, 0);
    timezones["PETT"] = Timezone("PETT", 12, 0);
    timezones["PGT"] = Timezone("PGT", 10, 0);
    timezones["PHOT"] = Timezone("PHOT", 13, 0);
    timezones["PHST"] = Timezone("PHST", 8, 0);
    timezones["PHT"] = Timezone("PHT", 8, 0);
    timezones["PKT"] = Timezone("PKT", 5, 0);
    timezones["PMDT"] = Timezone("PMDT", 2, 0);
    timezones["PMST"] = Timezone("PMST", 3, 0);
    timezones["PONT"] = Timezone("PONT", 11, 0);
    timezones["PST"] = Timezone("PST", 8, 0);
    timezones["PWT"] = Timezone("PWT", 9, 0);
    timezones["PYST"] = Timezone("PYST", 3, 0);
    timezones["PYT"] = Timezone("PYT", 4, 0);
    timezones["Pacific Daylight Time"] = Timezone("Pacific Daylight Time", 7, 0);
    timezones["Pacific Standard Time"] = Timezone("Pacific Standard Time", 8, 0);
    timezones["Pakistan Standard Time"] = Timezone("Pakistan Standard Time", 5, 0);
    timezones["Palau Time"] = Timezone("Palau Time", 9, 0);
    timezones["Papua New Guinea Time"] = Timezone("Papua New Guinea Time", 10, 0);
    timezones["Paraguay Summer Time"] = Timezone("Paraguay Summer Time", 3, 0);
    timezones["Paraguay Time"] = Timezone("Paraguay Time", 4, 0);
    timezones["Peru Time"] = Timezone("Peru Time", 5, 0);
    timezones["Philippine Standard Time"] = Timezone("Philippine Standard Time", 8, 0);
    timezones["Philippine Time"] = Timezone("Philippine Time", 8, 0);
    timezones["Phoenix Island Time"] = Timezone("Phoenix Island Time", 13, 0);
    timezones["Pohnpei Standard Time"] = Timezone("Pohnpei Standard Time", 11, 0);
    timezones["RET"] = Timezone("RET", 4, 0);
    timezones["ROTT"] = Timezone("ROTT", 3, 0);
    timezones["Rothera Research Station Time"] = Timezone("Rothera Research Station Time", 3, 0);
    timezones["Réunion Time"] = Timezone("Réunion Time", 4, 0);
    timezones["SAKT"] = Timezone("SAKT", 11, 0);
    timezones["SAMT"] = Timezone("SAMT", 4, 0);
    timezones["SAST"] = Timezone("SAST", 2, 0);
    timezones["SBT"] = Timezone("SBT", 11, 0);
    timezones["SCT"] = Timezone("SCT", 4, 0);
    timezones["SDT"] = Timezone("SDT", 10, 0);
    timezones["SGT"] = Timezone("SGT", 8, 0);
    timezones["SLST"] = Timezone("SLST", 5, 30);
    timezones["SRET"] = Timezone("SRET", 11, 0);
    timezones["SRT"] = Timezone("SRT", 3, 0);
    timezones["SST"] = Timezone("SST", 8, 0);
    timezones["SYOT"] = Timezone("SYOT", 3, 0);
    timezones["Saint Pierre and Miquelon Daylight Time"] = Timezone("Saint Pierre and Miquelon Daylight Time", 2, 0);
    timezones["Saint Pierre and Miquelon Standard Time"] = Timezone("Saint Pierre and Miquelon Standard Time", 3, 0);
    timezones["Sakhalin Island Time"] = Timezone("Sakhalin Island Time", 11, 0);
    timezones["Samara Time"] = Timezone("Samara Time", 4, 0);
    timezones["Samoa Daylight Time"] = Timezone("Samoa Daylight Time", 10, 0);
    timezones["Samoa Standard Time"] = Timezone("Samoa Standard Time", 11, 0);
    timezones["Seychelles Time"] = Timezone("Seychelles Time", 4, 0);
    timezones["Showa Station Time"] = Timezone("Showa Station Time", 3, 0);
    timezones["Singapore Standard Time"] = Timezone("Singapore Standard Time", 8, 0);
    timezones["Singapore Time"] = Timezone("Singapore Time", 8, 0);
    timezones["Solomon Islands Time"] = Timezone("Solomon Islands Time", 11, 0);
    timezones["South African Standard Time"] = Timezone("South African Standard Time", 2, 0);
    timezones["South Georgia and the South Sandwich Islands Time"] = Timezone("South Georgia and the South Sandwich Islands Time", 2, 0);
    timezones["Srednekolymsk Time"] = Timezone("Srednekolymsk Time", 11, 0);
    timezones["Sri Lanka Standard Time"] = Timezone("Sri Lanka Standard Time", 5, 30);
    timezones["Suriname Time"] = Timezone("Suriname Time", 3, 0);
    timezones["TAHT"] = Timezone("TAHT", 10, 0);
    timezones["TFT"] = Timezone("TFT", 5, 0);
    timezones["THA"] = Timezone("THA", 7, 0);
    timezones["TJT"] = Timezone("TJT", 5, 0);
    timezones["TKT"] = Timezone("TKT", 13, 0);
    timezones["TLT"] = Timezone("TLT", 9, 0);
    timezones["TMT"] = Timezone("TMT", 5, 0);
    timezones["TOT"] = Timezone("TOT", 13, 0);
    timezones["TRT"] = Timezone("TRT", 3, 0);
    timezones["TVT"] = Timezone("TVT", 12, 0);
    timezones["Tahiti Time"] = Timezone("Tahiti Time", 10, 0);
    timezones["Tajikistan Time"] = Timezone("Tajikistan Time", 5, 0);
    timezones["Thailand Standard Time"] = Timezone("Thailand Standard Time", 7, 0);
    timezones["Timor Leste Time"] = Timezone("Timor Leste Time", 9, 0);
    timezones["Tokelau Time"] = Timezone("Tokelau Time", 13, 0);
    timezones["Tonga Time"] = Timezone("Tonga Time", 13, 0);
    timezones["Turkey Time"] = Timezone("Turkey Time", 3, 0);
    timezones["Turkmenistan Time"] = Timezone("Turkmenistan Time", 5, 0);
    timezones["Tuvalu Time"] = Timezone("Tuvalu Time", 12, 0);
    timezones["ULAST"] = Timezone("ULAST", 9, 0);
    timezones["ULAT"] = Timezone("ULAT", 8, 0);
    timezones["UTC"] = Timezone("UTC", 0, 0);
    timezones["UYST"] = Timezone("UYST", 2, 0);
    timezones["UYT"] = Timezone("UYT", 3, 0);
    timezones["UZT"] = Timezone("UZT", 5, 0);
    timezones["Ulaanbaatar Standard Time"] = Timezone("Ulaanbaatar Standard Time", 8, 0);
    timezones["Ulaanbaatar Summer Time"] = Timezone("Ulaanbaatar Summer Time", 9, 0);
    timezones["Uruguay Standard Time"] = Timezone("Uruguay Standard Time", 3, 0);
    timezones["Uruguay Summer Time"] = Timezone("Uruguay Summer Time", 2, 0);
    timezones["Uzbekistan Time"] = Timezone("Uzbekistan Time", 5, 0);
    timezones["VET"] = Timezone("VET", 4, 0);
    timezones["VLAT"] = Timezone("VLAT", 10, 0);
    timezones["VOLT"] = Timezone("VOLT", 3, 0);
    timezones["VOST"] = Timezone("VOST", 6, 0);
    timezones["VUT"] = Timezone("VUT", 11, 0);
    timezones["Vanuatu"] = Timezone("Vanuatu", 11, 0);
    timezones["Venezuelan Standard Time"] = Timezone("Venezuelan Standard Time", 4, 0);
    timezones["Vladivostok Time"] = Timezone("Vladivostok Time", 10, 0);
    timezones["Volgograd Time"] = Timezone("Volgograd Time", 3, 0);
    timezones["Vostok Station Time"] = Timezone("Vostok Station Time", 6, 0);
    timezones["WAKT"] = Timezone("WAKT", 12, 0);
    timezones["WAST"] = Timezone("WAST", 2, 0);
    timezones["WAT"] = Timezone("WAT", 1, 0);
    timezones["WEST"] = Timezone("WEST", 1, 0);
    timezones["WET"] = Timezone("WET", 0, 0);
    timezones["WGST"] = Timezone("WGST", 2, 0);
    timezones["WGT"] = Timezone("WGT", 3, 0);
    timezones["WIB"] = Timezone("WIB", 7, 0);
    timezones["WIT"] = Timezone("WIT", 9, 0);
    timezones["WITA"] = Timezone("WITA", 8, 0);
    timezones["WST"] = Timezone("WST", 8, 0);
    timezones["Wake Island Time"] = Timezone("Wake Island Time", 12, 0);
    timezones["West Africa Summer Time"] = Timezone("West Africa Summer Time", 2, 0);
    timezones["West Africa Time"] = Timezone("West Africa Time", 1, 0);
    timezones["West Greenland Summer Time"] = Timezone("West Greenland Summer Time", 2, 0);
    timezones["West Greenland Time"] = Timezone("West Greenland Time", 3, 0);
    timezones["Western European Summer Time"] = Timezone("Western European Summer Time", 1, 0);
    timezones["Western European Time"] = Timezone("Western European Time", 0, 0);
    timezones["Western Indonesian Time"] = Timezone("Western Indonesian Time", 7, 0);
    timezones["Western Standard Time"] = Timezone("Western Standard Time", 8, 0);
    timezones["YAKT"] = Timezone("YAKT", 9, 0);
    timezones["YEKT"] = Timezone("YEKT", 5, 0);
    timezones["Yakutsk Time"] = Timezone("Yakutsk Time", 9, 0);
    timezones["Yekaterinburg Time"] = Timezone("Yekaterinburg Time", 5, 0);

    initialized = true;
    return timezones;
}

struct ACDT_Timezone: public BaseTimezone {
    ACDT_Timezone(): BaseTimezone() {
        tz = TZ("ACDT");
    }
};
struct ACST_Timezone: public BaseTimezone {
    ACST_Timezone(): BaseTimezone() {
        tz = TZ("ACST");
    }
};
struct ACT_Timezone: public BaseTimezone {
    ACT_Timezone(): BaseTimezone() {
        tz = TZ("ACT");
    }
};
struct ACWST_Timezone: public BaseTimezone {
    ACWST_Timezone(): BaseTimezone() {
        tz = TZ("ACWST");
    }
};
struct ADT_Timezone: public BaseTimezone {
    ADT_Timezone(): BaseTimezone() {
        tz = TZ("ADT");
    }
};
struct AEDT_Timezone: public BaseTimezone {
    AEDT_Timezone(): BaseTimezone() {
        tz = TZ("AEDT");
    }
};
struct AEST_Timezone: public BaseTimezone {
    AEST_Timezone(): BaseTimezone() {
        tz = TZ("AEST");
    }
};
struct AFT_Timezone: public BaseTimezone {
    AFT_Timezone(): BaseTimezone() {
        tz = TZ("AFT");
    }
};
struct AKDT_Timezone: public BaseTimezone {
    AKDT_Timezone(): BaseTimezone() {
        tz = TZ("AKDT");
    }
};
struct AKST_Timezone: public BaseTimezone {
    AKST_Timezone(): BaseTimezone() {
        tz = TZ("AKST");
    }
};
struct ALMT_Timezone: public BaseTimezone {
    ALMT_Timezone(): BaseTimezone() {
        tz = TZ("ALMT");
    }
};
struct AMST_Timezone: public BaseTimezone {
    AMST_Timezone(): BaseTimezone() {
        tz = TZ("AMST");
    }
};
struct AMT_Timezone: public BaseTimezone {
    AMT_Timezone(): BaseTimezone() {
        tz = TZ("AMT");
    }
};
struct ANAT_Timezone: public BaseTimezone {
    ANAT_Timezone(): BaseTimezone() {
        tz = TZ("ANAT");
    }
};
struct AQTT_Timezone: public BaseTimezone {
    AQTT_Timezone(): BaseTimezone() {
        tz = TZ("AQTT");
    }
};
struct ART_Timezone: public BaseTimezone {
    ART_Timezone(): BaseTimezone() {
        tz = TZ("ART");
    }
};
struct AST_Timezone: public BaseTimezone {
    AST_Timezone(): BaseTimezone() {
        tz = TZ("AST");
    }
};
struct AWST_Timezone: public BaseTimezone {
    AWST_Timezone(): BaseTimezone() {
        tz = TZ("AWST");
    }
};
struct AZOST_Timezone: public BaseTimezone {
    AZOST_Timezone(): BaseTimezone() {
        tz = TZ("AZOST");
    }
};
struct AZOT_Timezone: public BaseTimezone {
    AZOT_Timezone(): BaseTimezone() {
        tz = TZ("AZOT");
    }
};
struct AZT_Timezone: public BaseTimezone {
    AZT_Timezone(): BaseTimezone() {
        tz = TZ("AZT");
    }
};
struct BIOT_Timezone: public BaseTimezone {
    BIOT_Timezone(): BaseTimezone() {
        tz = TZ("BIOT");
    }
};
struct BIT_Timezone: public BaseTimezone {
    BIT_Timezone(): BaseTimezone() {
        tz = TZ("BIT");
    }
};
struct BNT_Timezone: public BaseTimezone {
    BNT_Timezone(): BaseTimezone() {
        tz = TZ("BNT");
    }
};
struct BOT_Timezone: public BaseTimezone {
    BOT_Timezone(): BaseTimezone() {
        tz = TZ("BOT");
    }
};
struct BRST_Timezone: public BaseTimezone {
    BRST_Timezone(): BaseTimezone() {
        tz = TZ("BRST");
    }
};
struct BRT_Timezone: public BaseTimezone {
    BRT_Timezone(): BaseTimezone() {
        tz = TZ("BRT");
    }
};
struct BST_Timezone: public BaseTimezone {
    BST_Timezone(): BaseTimezone() {
        tz = TZ("BST");
    }
};
struct BTT_Timezone: public BaseTimezone {
    BTT_Timezone(): BaseTimezone() {
        tz = TZ("BTT");
    }
};
struct CAT_Timezone: public BaseTimezone {
    CAT_Timezone(): BaseTimezone() {
        tz = TZ("CAT");
    }
};
struct CCT_Timezone: public BaseTimezone {
    CCT_Timezone(): BaseTimezone() {
        tz = TZ("CCT");
    }
};
struct CDT_Timezone: public BaseTimezone {
    CDT_Timezone(): BaseTimezone() {
        tz = TZ("CDT");
    }
};
struct CEST_Timezone: public BaseTimezone {
    CEST_Timezone(): BaseTimezone() {
        tz = TZ("CEST");
    }
};
struct CET_Timezone: public BaseTimezone {
    CET_Timezone(): BaseTimezone() {
        tz = TZ("CET");
    }
};
struct CHADT_Timezone: public BaseTimezone {
    CHADT_Timezone(): BaseTimezone() {
        tz = TZ("CHADT");
    }
};
struct CHAST_Timezone: public BaseTimezone {
    CHAST_Timezone(): BaseTimezone() {
        tz = TZ("CHAST");
    }
};
struct CHOST_Timezone: public BaseTimezone {
    CHOST_Timezone(): BaseTimezone() {
        tz = TZ("CHOST");
    }
};
struct CHOT_Timezone: public BaseTimezone {
    CHOT_Timezone(): BaseTimezone() {
        tz = TZ("CHOT");
    }
};
struct CHST_Timezone: public BaseTimezone {
    CHST_Timezone(): BaseTimezone() {
        tz = TZ("CHST");
    }
};
struct CHUT_Timezone: public BaseTimezone {
    CHUT_Timezone(): BaseTimezone() {
        tz = TZ("CHUT");
    }
};
struct CIST_Timezone: public BaseTimezone {
    CIST_Timezone(): BaseTimezone() {
        tz = TZ("CIST");
    }
};
struct CKT_Timezone: public BaseTimezone {
    CKT_Timezone(): BaseTimezone() {
        tz = TZ("CKT");
    }
};
struct CLST_Timezone: public BaseTimezone {
    CLST_Timezone(): BaseTimezone() {
        tz = TZ("CLST");
    }
};
struct CLT_Timezone: public BaseTimezone {
    CLT_Timezone(): BaseTimezone() {
        tz = TZ("CLT");
    }
};
struct COST_Timezone: public BaseTimezone {
    COST_Timezone(): BaseTimezone() {
        tz = TZ("COST");
    }
};
struct COT_Timezone: public BaseTimezone {
    COT_Timezone(): BaseTimezone() {
        tz = TZ("COT");
    }
};
struct CST_Timezone: public BaseTimezone {
    CST_Timezone(): BaseTimezone() {
        tz = TZ("CST");
    }
};
struct CVT_Timezone: public BaseTimezone {
    CVT_Timezone(): BaseTimezone() {
        tz = TZ("CVT");
    }
};
struct CWST_Timezone: public BaseTimezone {
    CWST_Timezone(): BaseTimezone() {
        tz = TZ("CWST");
    }
};
struct CXT_Timezone: public BaseTimezone {
    CXT_Timezone(): BaseTimezone() {
        tz = TZ("CXT");
    }
};
struct DAVT_Timezone: public BaseTimezone {
    DAVT_Timezone(): BaseTimezone() {
        tz = TZ("DAVT");
    }
};
struct DDUT_Timezone: public BaseTimezone {
    DDUT_Timezone(): BaseTimezone() {
        tz = TZ("DDUT");
    }
};
struct DFT_Timezone: public BaseTimezone {
    DFT_Timezone(): BaseTimezone() {
        tz = TZ("DFT");
    }
};
struct EASST_Timezone: public BaseTimezone {
    EASST_Timezone(): BaseTimezone() {
        tz = TZ("EASST");
    }
};
struct EAST_Timezone: public BaseTimezone {
    EAST_Timezone(): BaseTimezone() {
        tz = TZ("EAST");
    }
};
struct EAT_Timezone: public BaseTimezone {
    EAT_Timezone(): BaseTimezone() {
        tz = TZ("EAT");
    }
};
struct ECT_Timezone: public BaseTimezone {
    ECT_Timezone(): BaseTimezone() {
        tz = TZ("ECT");
    }
};
struct EDT_Timezone: public BaseTimezone {
    EDT_Timezone(): BaseTimezone() {
        tz = TZ("EDT");
    }
};
struct EEST_Timezone: public BaseTimezone {
    EEST_Timezone(): BaseTimezone() {
        tz = TZ("EEST");
    }
};
struct EET_Timezone: public BaseTimezone {
    EET_Timezone(): BaseTimezone() {
        tz = TZ("EET");
    }
};
struct EGST_Timezone: public BaseTimezone {
    EGST_Timezone(): BaseTimezone() {
        tz = TZ("EGST");
    }
};
struct EGT_Timezone: public BaseTimezone {
    EGT_Timezone(): BaseTimezone() {
        tz = TZ("EGT");
    }
};
struct EST_Timezone: public BaseTimezone {
    EST_Timezone(): BaseTimezone() {
        tz = TZ("EST");
    }
};
struct FET_Timezone: public BaseTimezone {
    FET_Timezone(): BaseTimezone() {
        tz = TZ("FET");
    }
};
struct FJT_Timezone: public BaseTimezone {
    FJT_Timezone(): BaseTimezone() {
        tz = TZ("FJT");
    }
};
struct FKST_Timezone: public BaseTimezone {
    FKST_Timezone(): BaseTimezone() {
        tz = TZ("FKST");
    }
};
struct FKT_Timezone: public BaseTimezone {
    FKT_Timezone(): BaseTimezone() {
        tz = TZ("FKT");
    }
};
struct FNT_Timezone: public BaseTimezone {
    FNT_Timezone(): BaseTimezone() {
        tz = TZ("FNT");
    }
};
struct GALT_Timezone: public BaseTimezone {
    GALT_Timezone(): BaseTimezone() {
        tz = TZ("GALT");
    }
};
struct GAMT_Timezone: public BaseTimezone {
    GAMT_Timezone(): BaseTimezone() {
        tz = TZ("GAMT");
    }
};
struct GET_Timezone: public BaseTimezone {
    GET_Timezone(): BaseTimezone() {
        tz = TZ("GET");
    }
};
struct GFT_Timezone: public BaseTimezone {
    GFT_Timezone(): BaseTimezone() {
        tz = TZ("GFT");
    }
};
struct GILT_Timezone: public BaseTimezone {
    GILT_Timezone(): BaseTimezone() {
        tz = TZ("GILT");
    }
};
struct GIT_Timezone: public BaseTimezone {
    GIT_Timezone(): BaseTimezone() {
        tz = TZ("GIT");
    }
};
struct GMT_Timezone: public BaseTimezone {
    GMT_Timezone(): BaseTimezone() {
        tz = TZ("GMT");
    }
};
struct GST_Timezone: public BaseTimezone {
    GST_Timezone(): BaseTimezone() {
        tz = TZ("GST");
    }
};
struct GYT_Timezone: public BaseTimezone {
    GYT_Timezone(): BaseTimezone() {
        tz = TZ("GYT");
    }
};
struct HAEC_Timezone: public BaseTimezone {
    HAEC_Timezone(): BaseTimezone() {
        tz = TZ("HAEC");
    }
};
struct HDT_Timezone: public BaseTimezone {
    HDT_Timezone(): BaseTimezone() {
        tz = TZ("HDT");
    }
};
struct HKT_Timezone: public BaseTimezone {
    HKT_Timezone(): BaseTimezone() {
        tz = TZ("HKT");
    }
};
struct HMT_Timezone: public BaseTimezone {
    HMT_Timezone(): BaseTimezone() {
        tz = TZ("HMT");
    }
};
struct HOVST_Timezone: public BaseTimezone {
    HOVST_Timezone(): BaseTimezone() {
        tz = TZ("HOVST");
    }
};
struct HOVT_Timezone: public BaseTimezone {
    HOVT_Timezone(): BaseTimezone() {
        tz = TZ("HOVT");
    }
};
struct HST_Timezone: public BaseTimezone {
    HST_Timezone(): BaseTimezone() {
        tz = TZ("HST");
    }
};
struct ICT_Timezone: public BaseTimezone {
    ICT_Timezone(): BaseTimezone() {
        tz = TZ("ICT");
    }
};
struct IDLW_Timezone: public BaseTimezone {
    IDLW_Timezone(): BaseTimezone() {
        tz = TZ("IDLW");
    }
};
struct IDT_Timezone: public BaseTimezone {
    IDT_Timezone(): BaseTimezone() {
        tz = TZ("IDT");
    }
};
struct IOT_Timezone: public BaseTimezone {
    IOT_Timezone(): BaseTimezone() {
        tz = TZ("IOT");
    }
};
struct IRDT_Timezone: public BaseTimezone {
    IRDT_Timezone(): BaseTimezone() {
        tz = TZ("IRDT");
    }
};
struct IRKT_Timezone: public BaseTimezone {
    IRKT_Timezone(): BaseTimezone() {
        tz = TZ("IRKT");
    }
};
struct IRST_Timezone: public BaseTimezone {
    IRST_Timezone(): BaseTimezone() {
        tz = TZ("IRST");
    }
};
struct IST_Timezone: public BaseTimezone {
    IST_Timezone(): BaseTimezone() {
        tz = TZ("IST");
    }
};
struct JST_Timezone: public BaseTimezone {
    JST_Timezone(): BaseTimezone() {
        tz = TZ("JST");
    }
};
struct KALT_Timezone: public BaseTimezone {
    KALT_Timezone(): BaseTimezone() {
        tz = TZ("KALT");
    }
};
struct KGT_Timezone: public BaseTimezone {
    KGT_Timezone(): BaseTimezone() {
        tz = TZ("KGT");
    }
};
struct KOST_Timezone: public BaseTimezone {
    KOST_Timezone(): BaseTimezone() {
        tz = TZ("KOST");
    }
};
struct KRAT_Timezone: public BaseTimezone {
    KRAT_Timezone(): BaseTimezone() {
        tz = TZ("KRAT");
    }
};
struct KST_Timezone: public BaseTimezone {
    KST_Timezone(): BaseTimezone() {
        tz = TZ("KST");
    }
};
struct LHST_Timezone: public BaseTimezone {
    LHST_Timezone(): BaseTimezone() {
        tz = TZ("LHST");
    }
};
struct LINT_Timezone: public BaseTimezone {
    LINT_Timezone(): BaseTimezone() {
        tz = TZ("LINT");
    }
};
struct MAGT_Timezone: public BaseTimezone {
    MAGT_Timezone(): BaseTimezone() {
        tz = TZ("MAGT");
    }
};
struct MART_Timezone: public BaseTimezone {
    MART_Timezone(): BaseTimezone() {
        tz = TZ("MART");
    }
};
struct MAWT_Timezone: public BaseTimezone {
    MAWT_Timezone(): BaseTimezone() {
        tz = TZ("MAWT");
    }
};
struct MDT_Timezone: public BaseTimezone {
    MDT_Timezone(): BaseTimezone() {
        tz = TZ("MDT");
    }
};
struct MEST_Timezone: public BaseTimezone {
    MEST_Timezone(): BaseTimezone() {
        tz = TZ("MEST");
    }
};
struct MET_Timezone: public BaseTimezone {
    MET_Timezone(): BaseTimezone() {
        tz = TZ("MET");
    }
};
struct MHT_Timezone: public BaseTimezone {
    MHT_Timezone(): BaseTimezone() {
        tz = TZ("MHT");
    }
};
struct MIST_Timezone: public BaseTimezone {
    MIST_Timezone(): BaseTimezone() {
        tz = TZ("MIST");
    }
};
struct MIT_Timezone: public BaseTimezone {
    MIT_Timezone(): BaseTimezone() {
        tz = TZ("MIT");
    }
};
struct MMT_Timezone: public BaseTimezone {
    MMT_Timezone(): BaseTimezone() {
        tz = TZ("MMT");
    }
};
struct MSK_Timezone: public BaseTimezone {
    MSK_Timezone(): BaseTimezone() {
        tz = TZ("MSK");
    }
};
struct MST_Timezone: public BaseTimezone {
    MST_Timezone(): BaseTimezone() {
        tz = TZ("MST");
    }
};
struct MUT_Timezone: public BaseTimezone {
    MUT_Timezone(): BaseTimezone() {
        tz = TZ("MUT");
    }
};
struct MVT_Timezone: public BaseTimezone {
    MVT_Timezone(): BaseTimezone() {
        tz = TZ("MVT");
    }
};
struct MYT_Timezone: public BaseTimezone {
    MYT_Timezone(): BaseTimezone() {
        tz = TZ("MYT");
    }
};
struct NCT_Timezone: public BaseTimezone {
    NCT_Timezone(): BaseTimezone() {
        tz = TZ("NCT");
    }
};
struct NDT_Timezone: public BaseTimezone {
    NDT_Timezone(): BaseTimezone() {
        tz = TZ("NDT");
    }
};
struct NFT_Timezone: public BaseTimezone {
    NFT_Timezone(): BaseTimezone() {
        tz = TZ("NFT");
    }
};
struct NOVT_Timezone: public BaseTimezone {
    NOVT_Timezone(): BaseTimezone() {
        tz = TZ("NOVT");
    }
};
struct NPT_Timezone: public BaseTimezone {
    NPT_Timezone(): BaseTimezone() {
        tz = TZ("NPT");
    }
};
struct NST_Timezone: public BaseTimezone {
    NST_Timezone(): BaseTimezone() {
        tz = TZ("NST");
    }
};
struct NT_Timezone: public BaseTimezone {
    NT_Timezone(): BaseTimezone() {
        tz = TZ("NT");
    }
};
struct NUT_Timezone: public BaseTimezone {
    NUT_Timezone(): BaseTimezone() {
        tz = TZ("NUT");
    }
};
struct NZDT_Timezone: public BaseTimezone {
    NZDT_Timezone(): BaseTimezone() {
        tz = TZ("NZDT");
    }
};
struct NZST_Timezone: public BaseTimezone {
    NZST_Timezone(): BaseTimezone() {
        tz = TZ("NZST");
    }
};
struct OMST_Timezone: public BaseTimezone {
    OMST_Timezone(): BaseTimezone() {
        tz = TZ("OMST");
    }
};
struct ORAT_Timezone: public BaseTimezone {
    ORAT_Timezone(): BaseTimezone() {
        tz = TZ("ORAT");
    }
};
struct PDT_Timezone: public BaseTimezone {
    PDT_Timezone(): BaseTimezone() {
        tz = TZ("PDT");
    }
};
struct PET_Timezone: public BaseTimezone {
    PET_Timezone(): BaseTimezone() {
        tz = TZ("PET");
    }
};
struct PETT_Timezone: public BaseTimezone {
    PETT_Timezone(): BaseTimezone() {
        tz = TZ("PETT");
    }
};
struct PGT_Timezone: public BaseTimezone {
    PGT_Timezone(): BaseTimezone() {
        tz = TZ("PGT");
    }
};
struct PHOT_Timezone: public BaseTimezone {
    PHOT_Timezone(): BaseTimezone() {
        tz = TZ("PHOT");
    }
};
struct PHST_Timezone: public BaseTimezone {
    PHST_Timezone(): BaseTimezone() {
        tz = TZ("PHST");
    }
};
struct PHT_Timezone: public BaseTimezone {
    PHT_Timezone(): BaseTimezone() {
        tz = TZ("PHT");
    }
};
struct PKT_Timezone: public BaseTimezone {
    PKT_Timezone(): BaseTimezone() {
        tz = TZ("PKT");
    }
};
struct PMDT_Timezone: public BaseTimezone {
    PMDT_Timezone(): BaseTimezone() {
        tz = TZ("PMDT");
    }
};
struct PMST_Timezone: public BaseTimezone {
    PMST_Timezone(): BaseTimezone() {
        tz = TZ("PMST");
    }
};
struct PONT_Timezone: public BaseTimezone {
    PONT_Timezone(): BaseTimezone() {
        tz = TZ("PONT");
    }
};
struct PST_Timezone: public BaseTimezone {
    PST_Timezone(): BaseTimezone() {
        tz = TZ("PST");
    }
};
struct PWT_Timezone: public BaseTimezone {
    PWT_Timezone(): BaseTimezone() {
        tz = TZ("PWT");
    }
};
struct PYST_Timezone: public BaseTimezone {
    PYST_Timezone(): BaseTimezone() {
        tz = TZ("PYST");
    }
};
struct PYT_Timezone: public BaseTimezone {
    PYT_Timezone(): BaseTimezone() {
        tz = TZ("PYT");
    }
};
struct RET_Timezone: public BaseTimezone {
    RET_Timezone(): BaseTimezone() {
        tz = TZ("RET");
    }
};
struct ROTT_Timezone: public BaseTimezone {
    ROTT_Timezone(): BaseTimezone() {
        tz = TZ("ROTT");
    }
};
struct SAKT_Timezone: public BaseTimezone {
    SAKT_Timezone(): BaseTimezone() {
        tz = TZ("SAKT");
    }
};
struct SAMT_Timezone: public BaseTimezone {
    SAMT_Timezone(): BaseTimezone() {
        tz = TZ("SAMT");
    }
};
struct SAST_Timezone: public BaseTimezone {
    SAST_Timezone(): BaseTimezone() {
        tz = TZ("SAST");
    }
};
struct SBT_Timezone: public BaseTimezone {
    SBT_Timezone(): BaseTimezone() {
        tz = TZ("SBT");
    }
};
struct SCT_Timezone: public BaseTimezone {
    SCT_Timezone(): BaseTimezone() {
        tz = TZ("SCT");
    }
};
struct SDT_Timezone: public BaseTimezone {
    SDT_Timezone(): BaseTimezone() {
        tz = TZ("SDT");
    }
};
struct SGT_Timezone: public BaseTimezone {
    SGT_Timezone(): BaseTimezone() {
        tz = TZ("SGT");
    }
};
struct SLST_Timezone: public BaseTimezone {
    SLST_Timezone(): BaseTimezone() {
        tz = TZ("SLST");
    }
};
struct SRET_Timezone: public BaseTimezone {
    SRET_Timezone(): BaseTimezone() {
        tz = TZ("SRET");
    }
};
struct SRT_Timezone: public BaseTimezone {
    SRT_Timezone(): BaseTimezone() {
        tz = TZ("SRT");
    }
};
struct SST_Timezone: public BaseTimezone {
    SST_Timezone(): BaseTimezone() {
        tz = TZ("SST");
    }
};
struct SYOT_Timezone: public BaseTimezone {
    SYOT_Timezone(): BaseTimezone() {
        tz = TZ("SYOT");
    }
};
struct TAHT_Timezone: public BaseTimezone {
    TAHT_Timezone(): BaseTimezone() {
        tz = TZ("TAHT");
    }
};
struct TFT_Timezone: public BaseTimezone {
    TFT_Timezone(): BaseTimezone() {
        tz = TZ("TFT");
    }
};
struct THA_Timezone: public BaseTimezone {
    THA_Timezone(): BaseTimezone() {
        tz = TZ("THA");
    }
};
struct TJT_Timezone: public BaseTimezone {
    TJT_Timezone(): BaseTimezone() {
        tz = TZ("TJT");
    }
};
struct TKT_Timezone: public BaseTimezone {
    TKT_Timezone(): BaseTimezone() {
        tz = TZ("TKT");
    }
};
struct TLT_Timezone: public BaseTimezone {
    TLT_Timezone(): BaseTimezone() {
        tz = TZ("TLT");
    }
};
struct TMT_Timezone: public BaseTimezone {
    TMT_Timezone(): BaseTimezone() {
        tz = TZ("TMT");
    }
};
struct TOT_Timezone: public BaseTimezone {
    TOT_Timezone(): BaseTimezone() {
        tz = TZ("TOT");
    }
};
struct TRT_Timezone: public BaseTimezone {
    TRT_Timezone(): BaseTimezone() {
        tz = TZ("TRT");
    }
};
struct TVT_Timezone: public BaseTimezone {
    TVT_Timezone(): BaseTimezone() {
        tz = TZ("TVT");
    }
};
struct ULAST_Timezone: public BaseTimezone {
    ULAST_Timezone(): BaseTimezone() {
        tz = TZ("ULAST");
    }
};
struct ULAT_Timezone: public BaseTimezone {
    ULAT_Timezone(): BaseTimezone() {
        tz = TZ("ULAT");
    }
};
struct UTC_Timezone: public BaseTimezone {
    UTC_Timezone(): BaseTimezone() {
        tz = TZ("UTC");
    }
};
struct UYST_Timezone: public BaseTimezone {
    UYST_Timezone(): BaseTimezone() {
        tz = TZ("UYST");
    }
};
struct UYT_Timezone: public BaseTimezone {
    UYT_Timezone(): BaseTimezone() {
        tz = TZ("UYT");
    }
};
struct UZT_Timezone: public BaseTimezone {
    UZT_Timezone(): BaseTimezone() {
        tz = TZ("UZT");
    }
};
struct VET_Timezone: public BaseTimezone {
    VET_Timezone(): BaseTimezone() {
        tz = TZ("VET");
    }
};
struct VLAT_Timezone: public BaseTimezone {
    VLAT_Timezone(): BaseTimezone() {
        tz = TZ("VLAT");
    }
};
struct VOLT_Timezone: public BaseTimezone {
    VOLT_Timezone(): BaseTimezone() {
        tz = TZ("VOLT");
    }
};
struct VOST_Timezone: public BaseTimezone {
    VOST_Timezone(): BaseTimezone() {
        tz = TZ("VOST");
    }
};
struct VUT_Timezone: public BaseTimezone {
    VUT_Timezone(): BaseTimezone() {
        tz = TZ("VUT");
    }
};
struct WAKT_Timezone: public BaseTimezone {
    WAKT_Timezone(): BaseTimezone() {
        tz = TZ("WAKT");
    }
};
struct WAST_Timezone: public BaseTimezone {
    WAST_Timezone(): BaseTimezone() {
        tz = TZ("WAST");
    }
};
struct WAT_Timezone: public BaseTimezone {
    WAT_Timezone(): BaseTimezone() {
        tz = TZ("WAT");
    }
};
struct WEST_Timezone: public BaseTimezone {
    WEST_Timezone(): BaseTimezone() {
        tz = TZ("WEST");
    }
};
struct WET_Timezone: public BaseTimezone {
    WET_Timezone(): BaseTimezone() {
        tz = TZ("WET");
    }
};
struct WGST_Timezone: public BaseTimezone {
    WGST_Timezone(): BaseTimezone() {
        tz = TZ("WGST");
    }
};
struct WGT_Timezone: public BaseTimezone {
    WGT_Timezone(): BaseTimezone() {
        tz = TZ("WGT");
    }
};
struct WIB_Timezone: public BaseTimezone {
    WIB_Timezone(): BaseTimezone() {
        tz = TZ("WIB");
    }
};
struct WIT_Timezone: public BaseTimezone {
    WIT_Timezone(): BaseTimezone() {
        tz = TZ("WIT");
    }
};
struct WITA_Timezone: public BaseTimezone {
    WITA_Timezone(): BaseTimezone() {
        tz = TZ("WITA");
    }
};
struct WST_Timezone: public BaseTimezone {
    WST_Timezone(): BaseTimezone() {
        tz = TZ("WST");
    }
};
struct YAKT_Timezone: public BaseTimezone {
    YAKT_Timezone(): BaseTimezone() {
        tz = TZ("YAKT");
    }
};
struct YEKT_Timezone: public BaseTimezone {
    YEKT_Timezone(): BaseTimezone() {
        tz = TZ("YEKT");
    }
};
struct UTCm12_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm12_Timezone(): BaseTimezone() {
        tz = TZ("UTC-12");
    }
};
struct UTCm1215_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm1215_Timezone(): BaseTimezone() {
        tz = TZ("UTC-12:15");
    }
};
struct UTCm1230_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm1230_Timezone(): BaseTimezone() {
        tz = TZ("UTC-12:30");
    }
};
struct UTCm1245_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm1245_Timezone(): BaseTimezone() {
        tz = TZ("UTC-12:45");
    }
};
struct UTCm11_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm11_Timezone(): BaseTimezone() {
        tz = TZ("UTC-11");
    }
};
struct UTCm1115_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm1115_Timezone(): BaseTimezone() {
        tz = TZ("UTC-11:15");
    }
};
struct UTCm1130_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm1130_Timezone(): BaseTimezone() {
        tz = TZ("UTC-11:30");
    }
};
struct UTCm1145_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm1145_Timezone(): BaseTimezone() {
        tz = TZ("UTC-11:45");
    }
};
struct UTCm10_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm10_Timezone(): BaseTimezone() {
        tz = TZ("UTC-10");
    }
};
struct UTCm1015_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm1015_Timezone(): BaseTimezone() {
        tz = TZ("UTC-10:15");
    }
};
struct UTCm1030_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm1030_Timezone(): BaseTimezone() {
        tz = TZ("UTC-10:30");
    }
};
struct UTCm1045_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm1045_Timezone(): BaseTimezone() {
        tz = TZ("UTC-10:45");
    }
};
struct UTCm9_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm9_Timezone(): BaseTimezone() {
        tz = TZ("UTC-9");
    }
};
struct UTCm915_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm915_Timezone(): BaseTimezone() {
        tz = TZ("UTC-9:15");
    }
};
struct UTCm930_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm930_Timezone(): BaseTimezone() {
        tz = TZ("UTC-9:30");
    }
};
struct UTCm945_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm945_Timezone(): BaseTimezone() {
        tz = TZ("UTC-9:45");
    }
};
struct UTCm8_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm8_Timezone(): BaseTimezone() {
        tz = TZ("UTC-8");
    }
};
struct UTCm815_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm815_Timezone(): BaseTimezone() {
        tz = TZ("UTC-8:15");
    }
};
struct UTCm830_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm830_Timezone(): BaseTimezone() {
        tz = TZ("UTC-8:30");
    }
};
struct UTCm845_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm845_Timezone(): BaseTimezone() {
        tz = TZ("UTC-8:45");
    }
};
struct UTCm7_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm7_Timezone(): BaseTimezone() {
        tz = TZ("UTC-7");
    }
};
struct UTCm715_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm715_Timezone(): BaseTimezone() {
        tz = TZ("UTC-7:15");
    }
};
struct UTCm730_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm730_Timezone(): BaseTimezone() {
        tz = TZ("UTC-7:30");
    }
};
struct UTCm745_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm745_Timezone(): BaseTimezone() {
        tz = TZ("UTC-7:45");
    }
};
struct UTCm6_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm6_Timezone(): BaseTimezone() {
        tz = TZ("UTC-6");
    }
};
struct UTCm615_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm615_Timezone(): BaseTimezone() {
        tz = TZ("UTC-6:15");
    }
};
struct UTCm630_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm630_Timezone(): BaseTimezone() {
        tz = TZ("UTC-6:30");
    }
};
struct UTCm645_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm645_Timezone(): BaseTimezone() {
        tz = TZ("UTC-6:45");
    }
};
struct UTCm5_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm5_Timezone(): BaseTimezone() {
        tz = TZ("UTC-5");
    }
};
struct UTCm515_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm515_Timezone(): BaseTimezone() {
        tz = TZ("UTC-5:15");
    }
};
struct UTCm530_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm530_Timezone(): BaseTimezone() {
        tz = TZ("UTC-5:30");
    }
};
struct UTCm545_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm545_Timezone(): BaseTimezone() {
        tz = TZ("UTC-5:45");
    }
};
struct UTCm4_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm4_Timezone(): BaseTimezone() {
        tz = TZ("UTC-4");
    }
};
struct UTCm415_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm415_Timezone(): BaseTimezone() {
        tz = TZ("UTC-4:15");
    }
};
struct UTCm430_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm430_Timezone(): BaseTimezone() {
        tz = TZ("UTC-4:30");
    }
};
struct UTCm445_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm445_Timezone(): BaseTimezone() {
        tz = TZ("UTC-4:45");
    }
};
struct UTCm3_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm3_Timezone(): BaseTimezone() {
        tz = TZ("UTC-3");
    }
};
struct UTCm315_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm315_Timezone(): BaseTimezone() {
        tz = TZ("UTC-3:15");
    }
};
struct UTCm330_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm330_Timezone(): BaseTimezone() {
        tz = TZ("UTC-3:30");
    }
};
struct UTCm345_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm345_Timezone(): BaseTimezone() {
        tz = TZ("UTC-3:45");
    }
};
struct UTCm2_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm2_Timezone(): BaseTimezone() {
        tz = TZ("UTC-2");
    }
};
struct UTCm215_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm215_Timezone(): BaseTimezone() {
        tz = TZ("UTC-2:15");
    }
};
struct UTCm230_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm230_Timezone(): BaseTimezone() {
        tz = TZ("UTC-2:30");
    }
};
struct UTCm245_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm245_Timezone(): BaseTimezone() {
        tz = TZ("UTC-2:45");
    }
};
struct UTCm1_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm1_Timezone(): BaseTimezone() {
        tz = TZ("UTC-1");
    }
};
struct UTCm115_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm115_Timezone(): BaseTimezone() {
        tz = TZ("UTC-1:15");
    }
};
struct UTCm130_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm130_Timezone(): BaseTimezone() {
        tz = TZ("UTC-1:30");
    }
};
struct UTCm145_Timezone: public BaseTimezone {
    Timezone tz;
    UTCm145_Timezone(): BaseTimezone() {
        tz = TZ("UTC-1:45");
    }
};
struct UTC0_Timezone: public BaseTimezone {
    Timezone tz;
    UTC0_Timezone(): BaseTimezone() {
        tz = TZ("UTC0");
    }
};
struct UTC015_Timezone: public BaseTimezone {
    Timezone tz;
    UTC015_Timezone(): BaseTimezone() {
        tz = TZ("UTC0:15");
    }
};
struct UTC030_Timezone: public BaseTimezone {
    Timezone tz;
    UTC030_Timezone(): BaseTimezone() {
        tz = TZ("UTC0:30");
    }
};
struct UTC045_Timezone: public BaseTimezone {
    Timezone tz;
    UTC045_Timezone(): BaseTimezone() {
        tz = TZ("UTC0:45");
    }
};
struct UTC1_Timezone: public BaseTimezone {
    Timezone tz;
    UTC1_Timezone(): BaseTimezone() {
        tz = TZ("UTC1");
    }
};
struct UTC115_Timezone: public BaseTimezone {
    Timezone tz;
    UTC115_Timezone(): BaseTimezone() {
        tz = TZ("UTC1:15");
    }
};
struct UTC130_Timezone: public BaseTimezone {
    Timezone tz;
    UTC130_Timezone(): BaseTimezone() {
        tz = TZ("UTC1:30");
    }
};
struct UTC145_Timezone: public BaseTimezone {
    Timezone tz;
    UTC145_Timezone(): BaseTimezone() {
        tz = TZ("UTC1:45");
    }
};
struct UTC2_Timezone: public BaseTimezone {
    Timezone tz;
    UTC2_Timezone(): BaseTimezone() {
        tz = TZ("UTC2");
    }
};
struct UTC215_Timezone: public BaseTimezone {
    Timezone tz;
    UTC215_Timezone(): BaseTimezone() {
        tz = TZ("UTC2:15");
    }
};
struct UTC230_Timezone: public BaseTimezone {
    Timezone tz;
    UTC230_Timezone(): BaseTimezone() {
        tz = TZ("UTC2:30");
    }
};
struct UTC245_Timezone: public BaseTimezone {
    Timezone tz;
    UTC245_Timezone(): BaseTimezone() {
        tz = TZ("UTC2:45");
    }
};
struct UTC3_Timezone: public BaseTimezone {
    Timezone tz;
    UTC3_Timezone(): BaseTimezone() {
        tz = TZ("UTC3");
    }
};
struct UTC315_Timezone: public BaseTimezone {
    Timezone tz;
    UTC315_Timezone(): BaseTimezone() {
        tz = TZ("UTC3:15");
    }
};
struct UTC330_Timezone: public BaseTimezone {
    Timezone tz;
    UTC330_Timezone(): BaseTimezone() {
        tz = TZ("UTC3:30");
    }
};
struct UTC345_Timezone: public BaseTimezone {
    Timezone tz;
    UTC345_Timezone(): BaseTimezone() {
        tz = TZ("UTC3:45");
    }
};
struct UTC4_Timezone: public BaseTimezone {
    Timezone tz;
    UTC4_Timezone(): BaseTimezone() {
        tz = TZ("UTC4");
    }
};
struct UTC415_Timezone: public BaseTimezone {
    Timezone tz;
    UTC415_Timezone(): BaseTimezone() {
        tz = TZ("UTC4:15");
    }
};
struct UTC430_Timezone: public BaseTimezone {
    Timezone tz;
    UTC430_Timezone(): BaseTimezone() {
        tz = TZ("UTC4:30");
    }
};
struct UTC445_Timezone: public BaseTimezone {
    Timezone tz;
    UTC445_Timezone(): BaseTimezone() {
        tz = TZ("UTC4:45");
    }
};
struct UTC5_Timezone: public BaseTimezone {
    Timezone tz;
    UTC5_Timezone(): BaseTimezone() {
        tz = TZ("UTC5");
    }
};
struct UTC515_Timezone: public BaseTimezone {
    Timezone tz;
    UTC515_Timezone(): BaseTimezone() {
        tz = TZ("UTC5:15");
    }
};
struct UTC530_Timezone: public BaseTimezone {
    Timezone tz;
    UTC530_Timezone(): BaseTimezone() {
        tz = TZ("UTC5:30");
    }
};
struct UTC545_Timezone: public BaseTimezone {
    Timezone tz;
    UTC545_Timezone(): BaseTimezone() {
        tz = TZ("UTC5:45");
    }
};
struct UTC6_Timezone: public BaseTimezone {
    Timezone tz;
    UTC6_Timezone(): BaseTimezone() {
        tz = TZ("UTC6");
    }
};
struct UTC615_Timezone: public BaseTimezone {
    Timezone tz;
    UTC615_Timezone(): BaseTimezone() {
        tz = TZ("UTC6:15");
    }
};
struct UTC630_Timezone: public BaseTimezone {
    Timezone tz;
    UTC630_Timezone(): BaseTimezone() {
        tz = TZ("UTC6:30");
    }
};
struct UTC645_Timezone: public BaseTimezone {
    Timezone tz;
    UTC645_Timezone(): BaseTimezone() {
        tz = TZ("UTC6:45");
    }
};
struct UTC7_Timezone: public BaseTimezone {
    Timezone tz;
    UTC7_Timezone(): BaseTimezone() {
        tz = TZ("UTC7");
    }
};
struct UTC715_Timezone: public BaseTimezone {
    Timezone tz;
    UTC715_Timezone(): BaseTimezone() {
        tz = TZ("UTC7:15");
    }
};
struct UTC730_Timezone: public BaseTimezone {
    Timezone tz;
    UTC730_Timezone(): BaseTimezone() {
        tz = TZ("UTC7:30");
    }
};
struct UTC745_Timezone: public BaseTimezone {
    Timezone tz;
    UTC745_Timezone(): BaseTimezone() {
        tz = TZ("UTC7:45");
    }
};
struct UTC8_Timezone: public BaseTimezone {
    Timezone tz;
    UTC8_Timezone(): BaseTimezone() {
        tz = TZ("UTC8");
    }
};
struct UTC815_Timezone: public BaseTimezone {
    Timezone tz;
    UTC815_Timezone(): BaseTimezone() {
        tz = TZ("UTC8:15");
    }
};
struct UTC830_Timezone: public BaseTimezone {
    Timezone tz;
    UTC830_Timezone(): BaseTimezone() {
        tz = TZ("UTC8:30");
    }
};
struct UTC845_Timezone: public BaseTimezone {
    Timezone tz;
    UTC845_Timezone(): BaseTimezone() {
        tz = TZ("UTC8:45");
    }
};
struct UTC9_Timezone: public BaseTimezone {
    Timezone tz;
    UTC9_Timezone(): BaseTimezone() {
        tz = TZ("UTC9");
    }
};
struct UTC915_Timezone: public BaseTimezone {
    Timezone tz;
    UTC915_Timezone(): BaseTimezone() {
        tz = TZ("UTC9:15");
    }
};
struct UTC930_Timezone: public BaseTimezone {
    Timezone tz;
    UTC930_Timezone(): BaseTimezone() {
        tz = TZ("UTC9:30");
    }
};
struct UTC945_Timezone: public BaseTimezone {
    Timezone tz;
    UTC945_Timezone(): BaseTimezone() {
        tz = TZ("UTC9:45");
    }
};
struct UTC10_Timezone: public BaseTimezone {
    Timezone tz;
    UTC10_Timezone(): BaseTimezone() {
        tz = TZ("UTC10");
    }
};
struct UTC1015_Timezone: public BaseTimezone {
    Timezone tz;
    UTC1015_Timezone(): BaseTimezone() {
        tz = TZ("UTC10:15");
    }
};
struct UTC1030_Timezone: public BaseTimezone {
    Timezone tz;
    UTC1030_Timezone(): BaseTimezone() {
        tz = TZ("UTC10:30");
    }
};
struct UTC1045_Timezone: public BaseTimezone {
    Timezone tz;
    UTC1045_Timezone(): BaseTimezone() {
        tz = TZ("UTC10:45");
    }
};
struct UTC11_Timezone: public BaseTimezone {
    Timezone tz;
    UTC11_Timezone(): BaseTimezone() {
        tz = TZ("UTC11");
    }
};
struct UTC1115_Timezone: public BaseTimezone {
    Timezone tz;
    UTC1115_Timezone(): BaseTimezone() {
        tz = TZ("UTC11:15");
    }
};
struct UTC1130_Timezone: public BaseTimezone {
    Timezone tz;
    UTC1130_Timezone(): BaseTimezone() {
        tz = TZ("UTC11:30");
    }
};
struct UTC1145_Timezone: public BaseTimezone {
    Timezone tz;
    UTC1145_Timezone(): BaseTimezone() {
        tz = TZ("UTC11:45");
    }
};
struct UTC12_Timezone: public BaseTimezone {
    Timezone tz;
    UTC12_Timezone(): BaseTimezone() {
        tz = TZ("UTC12");
    }
};
struct UTC1215_Timezone: public BaseTimezone {
    Timezone tz;
    UTC1215_Timezone(): BaseTimezone() {
        tz = TZ("UTC12:15");
    }
};
struct UTC1230_Timezone: public BaseTimezone {
    Timezone tz;
    UTC1230_Timezone(): BaseTimezone() {
        tz = TZ("UTC12:30");
    }
};
struct UTC1245_Timezone: public BaseTimezone {
    Timezone tz;
    UTC1245_Timezone(): BaseTimezone() {
        tz = TZ("UTC12:45");
    }
};
struct UTC13_Timezone: public BaseTimezone {
    Timezone tz;
    UTC13_Timezone(): BaseTimezone() {
        tz = TZ("UTC13");
    }
};
struct UTC1315_Timezone: public BaseTimezone {
    Timezone tz;
    UTC1315_Timezone(): BaseTimezone() {
        tz = TZ("UTC13:15");
    }
};
struct UTC1330_Timezone: public BaseTimezone {
    Timezone tz;
    UTC1330_Timezone(): BaseTimezone() {
        tz = TZ("UTC13:30");
    }
};
struct UTC1345_Timezone: public BaseTimezone {
    Timezone tz;
    UTC1345_Timezone(): BaseTimezone() {
        tz = TZ("UTC13:45");
    }
};
struct UTC14_Timezone: public BaseTimezone {
    Timezone tz;
    UTC14_Timezone(): BaseTimezone() {
        tz = TZ("UTC14");
    }
};
}
#endif /* X_DATETIME_TIMEZONE_H */
